package udpserver

import (
	"net"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
)

// parseResolvConf is the part of systemDNSUpstreams that can be tested without
// reaching into /etc: given the file's contents, which nameservers come out.
func parseResolvConf(t *testing.T, contents string) []string {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "resolv.conf")
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatal(err)
	}
	// Mirror of the parser in systemDNSUpstreams, pointed at a temp file. Kept
	// in step deliberately: the shape being checked is what a real resolv.conf
	// throws at it - comments, search lines, options, IPv6, junk.
	var got []string
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 || fields[0] != "nameserver" {
			continue
		}
		if net.ParseIP(fields[1]) == nil {
			continue
		}
		got = append(got, net.JoinHostPort(fields[1], "53"))
	}
	return got
}

func TestResolvConfParsingTakesOnlyRealNameservers(t *testing.T) {
	got := parseResolvConf(t, `
# generated by something
; another comment style
search lan example.com
options edns0 trust-ad
nameserver 127.0.0.53
nameserver 8.8.4.4
nameserver 2001:4860:4860::8888
nameserver not-an-ip
nameserver
domain lan
`)
	want := []string{"127.0.0.53:53", "8.8.4.4:53", "[2001:4860:4860::8888]:53"}
	if len(got) != len(want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("entry %d: got %q want %q (all: %v)", i, got[i], want[i], got)
		}
	}
}

// A resolv.conf with nothing usable must yield nothing, so the caller falls
// through to SERVFAIL rather than "resolving" against an empty list.
func TestResolvConfWithNoNameserversYieldsNothing(t *testing.T) {
	if got := parseResolvConf(t, "search lan\noptions ndots:1\n# nameserver 1.1.1.1\n"); len(got) != 0 {
		t.Fatalf("got %v, want none", got)
	}
}

// systemDNSUpstreams reads once and caches. Whatever this host has, asking
// twice must give the same slice - a per-query read of /etc/resolv.conf would
// be wasted work on the hot path.
func TestSystemDNSUpstreamsIsReadOnce(t *testing.T) {
	first := systemDNSUpstreams()
	second := systemDNSUpstreams()
	if len(first) != len(second) {
		t.Fatalf("two calls disagree: %v vs %v", first, second)
	}
	for i := range first {
		if first[i] != second[i] {
			t.Fatalf("entry %d differs between calls: %q vs %q", i, first[i], second[i])
		}
	}
	// The sync.Once must have fired regardless of what the file held.
	var zero sync.Once
	if systemResolversOnce == zero {
		t.Fatal("systemDNSUpstreams never ran its Once")
	}
}

// The fallback must only be reached when the configured upstreams produce
// nothing - a working upstream is the intent and must win.
func TestResolveDNSUpstreamPrefersConfiguredUpstreams(t *testing.T) {
	want := []byte("configured-answer")
	s := &Server{
		resolveDNSQueryFn: func([]byte) ([]byte, error) { return want, nil },
	}
	got, err := s.resolveDNSUpstream([]byte("query"))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if string(got) != string(want) {
		t.Fatalf("got %q, want the configured upstream's %q", got, want)
	}
}

// An empty query is not something to go asking the network about.
func TestResolveDNSUpstreamRejectsEmptyQuery(t *testing.T) {
	s := &Server{}
	if _, err := s.resolveDNSUpstream(nil); err == nil {
		t.Fatal("an empty query was accepted; it should be refused before any I/O")
	}
}
